### ISSUE TITLE
Failed to create display file object MSTDSP

### ISSUE THREAD

**Issue by angelorpa** [edmundreinhardt/payroll-bob#4]
Hi, I’m having an issue building the project. I cloned the repo into pub400 server and use the command: 

makei build -e pgmlib=ANGELORPA2 -e dtalib=ANGELORPA2 

bob crete the phisical files (tables) but at time to try to create the display file object from the MSTDSP.DSPF source code it fails,

The bob version in pub400 is 2.4.0, could be this a problem?

Is bob creating a temporal source file to converting the stream file source code of the display file into source member so it could be compiled? I was looking into bob source code to check if a CPYFRMSTMF is performed before the CRTDSPF but I didn’t founded it.

![image](https://user-images.githubusercontent.com/10833316/215863397-ba2f87ae-5e63-4056-9128-05fe0592d251.png)

**Comment by edmundreinhardt** [comment]
Yes under the covers the crtfrmstmf script is run to copy to a SRC-PF in  QTEMP
And then update the file iname in the EVENTF that is copied back.

The .evfevent directory in your project roots has the eventf for MSTDSP and will tell you what is wrong.
Also look at the output.log in the .logs directory which has all the command and compile listing.
Finally the .logs /joblog.json has all the job log in full detail.

If you use Merlin this is all exposed for you.

Code for I also pulls back the eventf and shows problem markers in the source for you.

Hope this helps,

Edmund

**Comment by angelorpa** [comment]
Thanks for the help.  Please, could you check the attached  image of the output.log content, I not sure but to me It seems the issue is due to pub400 server restrictions, if not please let me know if there are something that i coudl do to fix it. Thanks a lot.

![image](https://user-images.githubusercontent.com/10833316/216165047-f97b9df3-db37-4dd8-a966-c72978cee1e6.png)

**Comment by edmundreinhardt** [comment]
Hmm, let me look into this.
It looks like crtfrmstmf is trying to get the CCSID from the current job and is not authorized to do so.
In your case, defaulting to 37 would not be a good answer.

**Comment by edmundreinhardt** [comment]
Angelo, we are investigating, but the bottom line is that this is unique to PUB400 and that it should work on your own IBM i.  We will continue to figure out what is going on with bin/sh on PUB400


> I think the issue is more related to ‘/bin/sh’ than anything. /bin/sh is a symbolic link to an ILE program so there’s problems launching it from a PASE program in some environments.
> 
> Interestingly, Python does indeed explicitly go to /bin/sh. https://github.com/python/cpython/blob/ee21110086e277a0ac24f5f768f35847b4db3380/Lib/subprocess.py#L1763 
> I often forget that there’s some magic that will implicitly run the /QOpenSys/usr/bin variant for you. 
>  
> I can confirm, however, that this doesn’t work right on pub400, even outside of python, for instance from Qp2Term: 
> /bin/sh -c 'echo hi' 
> /QOpenSys/usr/bin/-sh: /bin/sh: 0403-006 Execute permission denied.  
> (the same command works on our dev machines)
>  
> Either a true permission issue or the /QOpenSys/usr/bin voodoo-facility is not working on pub400. The permission on /bin/sh is 777 and the ILE program is 705 on both oss73dev and pub400. My userid can invoke /QOpenSys/usr/bin/sh just fine.

**Comment by angelorpa** [comment]
I did some research and testing, so I did isoleted the code for _get_attr function and replaced the os.popen with subprocess.run to execute the attr command to get the CCSID of a stream file, the test shows it works well as worarround to fix the issue

![image](https://user-images.githubusercontent.com/10833316/216370002-de5ec979-19f1-460d-bfab-49709a66a453.png)

but subprocess.Popen works as well, and it's not a bloking operation like subprocess.run is

![image](https://user-images.githubusercontent.com/10833316/216386831-80a9dbc4-6788-4d3c-90ed-a02cb4a11821.png)

**Comment by edmundreinhardt** [comment]
Good news Angelo
we determined that this was a problem with PUB400 that the link from /bin/sh to /QOpenSys/bin was missing.


>Thanks, Kevin! /QOpenSys/bin indeed does not exist

**Comment by angelorpa** [comment]
Great, but the new question I have is why os.popen fails but subprocess.Popen works fine. See my previous [post](https://github.com/edmundreinhardt/payroll-bob/issues/4#issuecomment-1413950967)

**Comment by edmundreinhardt** [comment]
is it possible that Jesse Gorizinski fixed the broken link before you tried subprocess.Popen and now all ways work?
